name: pixabay_demo
description: "A demonstration application that implements mocked authentication and image fetching from pixabay"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  http_mock_adapter: ^0.6.1
  dio: ^5.7.0
  get_it: ^7.7.0
  hive: ^2.2.3
  shared_preferences: ^2.3.2
  go_router: ^14.2.7
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependency_overrides:
  flutter_localizations:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/en.json